### ISSUE TITLE
Build errors - missing packages

### ISSUE THREAD

**Issue by tmcsys** [ccavanaugh/jgnash#49] opened 2018-07-31 16:38 UTC
Could this build error have something to do with the recent naming of packages?

Task :jgnash-fx:compileJava
~/Repositories/jgnash/jgnash-fx/src/main/java/jgnash/uifx/views/register/RegisterActions.java:33: error: package jgnash.convert.out.csv does not exist
import jgnash.convert.out.csv.CsvExport;
                             ^
~/Repositories/jgnash/jgnash-fx/src/main/java/jgnash/uifx/views/register/RegisterActions.java:34: error: package jgnash.convert.out.ofx does not exist
import jgnash.convert.out.ofx.OfxExport;
                             ^
~/Repositories/jgnash/jgnash-fx/src/main/java/jgnash/uifx/views/register/RegisterActions.java:35: error: package jgnash.convert.out.ssf does not exist
import jgnash.convert.out.ssf.AccountExport;
                             ^
~/Repositories/jgnash/jgnash-fx/src/main/java/jgnash/uifx/views/register/RegisterActions.java:183: error: cannot find symbol
                        OfxExport export = new OfxExport(account, startDate, endDate, file);
                        ^
symbol: class OfxExport
~/Repositories/jgnash/jgnash-fx/src/main/java/jgnash/uifx/views/register/RegisterActions.java:183: error: cannot find symbol
                        OfxExport export = new OfxExport(account, startDate, endDate, file);
                                               ^
symbol: class OfxExport
~/Repositories/jgnash/jgnash-fx/src/main/java/jgnash/uifx/views/register/RegisterActions.java:186: error: cannot find symbol
                        AccountExport.exportAccount(account, RegisterFactory.getColumnNames(account.getAccountType()),
                        ^
symbol: variable AccountExport
~/Repositories/jgnash/jgnash-fx/src/main/java/jgnash/uifx/views/register/RegisterActions.java:189: error: cannot find symbol
                        CsvExport.exportAccount(account, startDate, endDate, file);
                        ^
symbol: variable CsvExport
7 errors

Task :jgnash-fx:compileJava FAILED

gradle 4.9 build
OSX 10.11.6
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Comment by tmcsys** [comment] 2018-08-01 20:10
Commit log shows Travis CI errors similar to the above for commit 20a0f71989e5b124ed6be625563248b409d3ff9f 

Travis CI builds are unsuccessful for all commits after July 28.

Project master builds successfully if checked out from commit 1abda460b789210238df9d96ccdd883c67e0344c

**Comment by ccavanaugh** [comment] 2018-08-02 08:51
I'm looking into this.... the gradle build completes normally on my system and an non-gradle compile within the IDE is correct also.

**Comment by ccavanaugh** [comment] 2018-08-02 09:45
It appears as if there was some type of refactoring corruption that was not in my local copy, but made it to github.  I suspect use of the 'out' package name was root cause.

**Comment by ccavanaugh** [comment] 2018-08-02 16:25
Should be fixed now.  There will an additional package name change for "in" to remain consistent.

**Closed by ccavanaugh** 2018-08-02 16:25 UTC
