### ISSUE TITLE
jGncash says "a new version is available" and never starts up.

### ISSUE THREAD

**Issue by valnaumov** [ccavanaugh/jgnash#18] opened 2016-11-12 01:47 UTC
Launched the fx version of jgnash today and that showed me a popup telling there is an update available. 
![jgnash](https://cloud.githubusercontent.com/assets/11170863/20234772/8f01019e-a8bc-11e6-81b7-8d18d4fabf9a.png)

After I close it the program hangs in task bar and don't show it's window even if click on it. I'm on Win10 LTSB 64. Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode). jGnash 2.26.1

**Comment by ccavanaugh** [comment] 2016-11-23 10:24
Does is hang when using the Fx interface?  From the looks of the screen shot, this looks like the older Swing interface.

**Comment by valnaumov** [comment] 2016-11-23 12:52
@ccavanaugh yes, that's fx.

**Comment by ccavanaugh** [comment] 2016-11-24 10:02
I've not been able to reproduce the issue on Windows 10 myself.  

However, some UI issues were addressed in the 2.27.0 release and I've just made some changes in when and how the dialog is displayed that is much less likely to freeze the primary UI.  Thanks for taking the time to report this.

**Closed by ccavanaugh** 2016-11-24 10:02 UTC
